name: artifact_action
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
     -  name: Code Checkout  
        uses: actions/checkout@v4
     -  name: Install Dependencies
        run: npm ci
     -  name: Test Code
        run: npm run test
  build-job:
    needs: [test-job]
    runs-on: ubuntu-latest
    steps:
     -  name: Code Checkout  
        uses: actions/checkout@v4
     -  name: Install Dependencies
        run: npm ci
     -  name: Build Code
        run: npm run build
     -  name: Package Build
        uses: actions/upload-artifact@v4
        with:
          name: my-react-artifact03
          path: dist
  deploy-job:
    needs: [build-job]
    runs-on: ubuntu-latest
    steps:
     -  name: Upload Code
        uses: actions/download-artifact@v4
        with:
          name: my-react-artifact03
          path: test-artifacts
     -  name: Check path
        run: ls test-artifacts/*
     -  name: Dummy Message
        run: echo "Successfully Deployed !!!"
